markdown: kramdown
pygments: true
url: http://pantumaca.com
title: Pantumaca
description: "Family doctor, inspired chef, Deutschschülerin and proud mom."
production_url: http://pantumaca.com
simple_search: http://www.duckduckgo.com/
author:
  name: María Suau
  github: mariasuau
  twitter: mariasuau
